
services:
  askdocs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - vector_db
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0

  vector_db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma

volumes:
  chroma_data: